server:
  port: 8090
spring:
  application:
    name: light-mall
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/light?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 'shiws1203'
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 5
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: "SELECT 'x'"
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 10
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    poolPreparedStatements: true
    keepAlive: true
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    encoding: UTF-8
    basename: message/messages_zh
  # 定位模板的目录,给返回的页面添加后缀名
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
# Logger Config
logging:
  level:
    com.vicente.lightMall: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'
# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间